# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_id', models.CharField(max_length=50, unique=True)),
                ('prev_real_rr', models.DecimalField(decimal_places=3, max_digits=6)),
                ('prev_predicted_rr', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
