# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='host_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='op_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='prev_predicted_rr',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='container',
            name='prev_real_rr',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
