# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180424_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='prev_art',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
