# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_container_prev_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
    ]
