# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_container_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='op_point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='container',
            name='prev_art',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='prev_predicted_rr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='container',
            name='prev_real_rr',
            field=models.FloatField(default=0),
        ),
    ]
