# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180425_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='next_pes',
            field=models.FloatField(default=0),
        ),
    ]
