# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_container_next_pes'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='next_real_rr',
            field=models.FloatField(default=0),
        ),
    ]
