# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_container_next_real_rr'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='acu_cpu',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='ticks',
            field=models.IntegerField(default=0),
        ),
    ]
