# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180427_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='prev_fin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='prev_rej',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='prev_subm',
            field=models.IntegerField(default=0),
        ),
    ]
