# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180427_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='next_real_rr',
            new_name='next_predicted_rr',
        ),
    ]
