# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180502_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='next_predicted_rr',
            new_name='next_rr_limit',
        ),
    ]
