# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180502_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='acu_cpu',
            new_name='accu_cpu',
        ),
        migrations.AddField(
            model_name='container',
            name='avg_cpu',
            field=models.FloatField(default=0),
        ),
    ]
