# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_container_prev_pes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.AlterField(
            model_name='container',
            name='app_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
