# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180705_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='next_predicted_rr',
        ),
    ]
